unit-test:
  image: amazoncorretto:11
  tags: [docker]
  script:
    # Maven Wrapper を使用する 
    - ./mvnw clean test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml