# image: amazoncorretto:11
image: docker:18.09.7

stages:
  - test

unit-test:
  stage: test
  tags: [docker]
  script:
    # Maven Wrapper を使用する 
    - ./mvnw clean test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

job-checkstyle:
  stage: test
  script:
    - ./mvnw checkstyle:checkstyle
  artifacts:
    when: always
    paths:
      - target/site/*
  tags: [docker]
  allow_failure: true
  except:
    - tags